stages:
  - test

# ะัะพััะพะน ัะตัั ะดะปั ะฟัะพะฒะตัะบะธ runner'ะฐ
test-runner:
  stage: test
  tags:
    - docker
    - linux
  script:
    - echo "๐ GitLab Runner ัะฐะฑะพัะฐะตั ะบะพััะตะบัะฝะพ!"
    - echo "๐ ะะฐัะฐ ะธ ะฒัะตะผั: $(date)"
    - echo "๐ง ะะฟะตัะฐัะธะพะฝะฝะฐั ัะธััะตะผะฐ: $(uname -a)"
    - echo "๐ณ Docker ะฒะตััะธั: $(docker --version)"
    - echo "๐ฆ Python ะฒะตััะธั: $(python --version 2>/dev/null || echo 'Python ะฝะต ัััะฐะฝะพะฒะปะตะฝ')"
    - echo "๐ง Git ะฒะตััะธั: $(git --version)"
    - echo "๐ ะขะตะบััะฐั ะดะธัะตะบัะพัะธั: $(pwd)"
    - echo "๐ค ะะพะปัะทะพะฒะฐัะตะปั: $(whoami)"
    - echo "โ ะัะต ะฟัะพะฒะตัะบะธ ะฟัะพะนะดะตะฝั ััะฟะตัะฝะพ!"
  only:
    - main
    - merge_requests
